# Generated by Django 4.0 on 2022-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersettings_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhandle',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialhandle',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialhandle',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
