# Generated by Django 4.0 on 2022-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usersettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='request_author_access_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
