# Generated by Django 4.0 on 2022-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_is_author_alter_usersettings_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
