# Generated by Django 4.0 on 2022-12-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usersettings_accepted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='request_author_access_date',
            new_name='requested_date',
        ),
    ]
