# Generated by Django 4.0 on 2023-01-31 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
