# Generated by Django 4.0 on 2023-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='share_liked_posts',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
