# Generated by Django 4.0 on 2023-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usersettings_share_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='share_liked_posts',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
