# Generated by Django 4.0 on 2022-12-08 11:37

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_usersettings_options'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(blank=True, default='#333', max_length=20, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('images', 'Images'), ('video', 'Video')], max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='posts/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('post_video', models.FileField(null=True, upload_to='posts/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('post_content', froala_editor.fields.FroalaField(null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='post_title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory')),
                ('post_author', models.ForeignKey(default='Author', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.user')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
