# Generated by Django 4.0 on 2022-12-20 03:42

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
