# Generated by Django 4.0 on 2022-11-10 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_gender'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AddField(
            model_name='postcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('images', 'Images'), ('video', 'Video')], max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('post_content', django_quill.fields.QuillField()),
                ('tags', models.CharField(max_length=150)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory')),
                ('post_author', models.ForeignKey(default='Author', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.user')),
            ],
        ),
    ]
