# Generated by Django 4.0 on 2022-12-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
