# Generated by Django 4.0 on 2022-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='color',
            field=models.CharField(blank=True, default='#333', max_length=20, null=True),
        ),
    ]
