# Generated by Django 4.0 on 2022-12-22 10:22

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcategory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='short_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
