# Generated by Django 4.0 on 2022-12-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcategory_slug_alter_postcategory_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=20, null=True),
        ),
    ]
