# Generated by Django 4.0 on 2023-01-13 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postcategory_emoji_alter_postcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
