# Generated by Django 4.0 on 2023-01-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='post',
            new_name='posts',
        ),
    ]
