# Generated by Django 4.0 on 2023-01-15 03:06

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_favourites_delete_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
