# Generated by Django 4.0 on 2023-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('images', 'Images'), ('video', 'Video')], max_length=50, null=True),
        ),
    ]
