# Generated by Django 4.0 on 2023-01-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_post_image_alter_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favourites',
            new_name='bookmarks',
        ),
    ]
