# Generated by Django 4.0 on 2023-02-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_video',
        ),
    ]
